host:
    addr: :8005
    https: false
profiles:
    p1:
      label: my_label
      keys:
        key1:
          gpio: '101010'
          macro: asdf_updated
    
macros:
    my_label:
        label: my_label
        command: asdf_updated
    another_label:
        label: another_label
        command: another_command
